language: node_js
node_js:
- node
cache: npm
env:
  global: 
script:
- rm -rf $TRAVIS_BUILD_DIR/build
- npm run build
after_success:
- curl --ftp-create-dirs -T filename sftp://${SFTP_USER}:${SFTP_PASSWORD}@faloladare.com.ng/public_html/filename
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r $TRAVIS_BUILD_DIR/build/* ${SSH_USER}@${SSH_HOST}:/${DEPLOY_DIR}
  on:
    branch: master
  local_dir: build
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_cf62f93d0aa8_key -iv $encrypted_cf62f93d0aa8_iv
  -in id_rsa2.enc -out .travis/id_rsa2 -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa2
- ssh-add .travis/id_rsa2
- echo -e "Host ${SSH_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
